include:
  - ".well-known"
  - ".htaccess"

# Exclude these files from production site
exclude:
  - package.json
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .kiro

plugins:
  - jekyll-sitemap

# Output options
timezone: America/Sao_Paulo
encoding: UTF-8
layout: default

# Name of website
title: Sulbeef Representações
noindex: true

baseurl: ""

